---
title: Simulating Monopoly - Part 2
author: ''
date: '2021-01-27'
slug: []
categories: []
tags: []
description: ''
topics: []
---

<script src="index_files/header-attrs/header-attrs.js"></script>
<link href="index_files/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="index_files/anchor-sections/anchor-sections.js"></script>
<script src="index_files/kePrint/kePrint.js"></script>
<link href="index_files/lightable/lightable.css" rel="stylesheet" />
<link href="index_files/bsTable/bootstrapTable.min.css" rel="stylesheet" />
<script src="index_files/bsTable/bootstrapTable.js"></script>
<script src="index_files/htmlwidgets/htmlwidgets.js"></script>
<script src="index_files/jquery/jquery.min.js"></script>
<link href="index_files/datatables-css/datatables-crosstalk.css" rel="stylesheet" />
<script src="index_files/datatables-binding/datatables.js"></script>
<link href="index_files/dt-core/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="index_files/dt-core/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="index_files/dt-core/js/jquery.dataTables.min.js"></script>
<link href="index_files/nouislider/jquery.nouislider.min.css" rel="stylesheet" />
<script src="index_files/nouislider/jquery.nouislider.min.js"></script>
<link href="index_files/selectize/selectize.bootstrap3.css" rel="stylesheet" />
<script src="index_files/selectize/selectize.min.js"></script>
<link href="index_files/crosstalk/css/crosstalk.css" rel="stylesheet" />
<script src="index_files/crosstalk/js/crosstalk.min.js"></script>


<p>This is the second part in a two part series of looking at the game monopoly. If you haven’t read part one, then click here to read the post. I will now assume you are familiar with monopoly and how the simulation was built.</p>
<p>Previously we built a simulation of Monopoly and found that the most likeliest properties a player ends a dice roll on, that are also purchasable are: Trafalgar Square, Vine Street, and Stations.</p>
<p>The least likeliest are Old Kent Road, Whitechapel Road, and Park Lane.</p>
<p>In this post we will discuss the properties that are the best or worst depending on the metrics and scenarios we want to look at.</p>
<p>First I will quickly load in the required data.</p>
<pre class="r"><code>library(tidyverse)
library(patchwork)
library(ggtext)

monopoly_props &lt;-  readxl::read_xlsx(here::here(&quot;static/data/monpoly_properties.xlsx&quot;))



color_codes &lt;-  c(&quot;None&quot;=&quot;grey40&quot;,
                  &quot;Brown&quot; = &quot;#946C6B&quot;,
                  &quot;Station&quot;=&quot;#AEC7D8&quot;,#   &quot;#E3E4E5&quot;,
                  &quot;Light Blue&quot;= &quot;#79D7D8&quot;,
                  &quot;Pink&quot; =&quot;#ED63DF&quot;,# &quot;#E51AD0&quot;,
                  &quot;Utilities&quot; = &quot;#4CB45C&quot;,# &quot;#7FCA8B&quot;,
                  &quot;Orange&quot; = &quot;#E4901B&quot;,
                  &quot;Red&quot;=&quot;#E71A18&quot;,
                  &quot;Yellow&quot; = &quot;#FFDC00&quot;,
                  &quot;Green&quot; = &quot;#097F09&quot;,
                  &quot;Dark Blue&quot; = &quot;#1F4AE0&quot;
                  )

options(kableExtra.html.bsTable = TRUE)</code></pre>
<p>We recall that in the first blogpost we had 4 difference scenarios:</p>
<ul>
<li><p>The long term state of the board after many dice rolls, with a strategy of leaving jail as soon as possible</p></li>
<li><p>The long term state of the board after many dice rolls, with a strategy of staying in jail as long as possible</p></li>
<li><p>The state of the board after 30 dice rolls, with a strategy of leaving jail as soon as possible</p></li>
<li><p>The state of the board after 30 dice rolls, with a strategy of staying in jail as long as possible</p></li>
</ul>
<p>Where <span class="math inline">\(\text{many dice rolls} \gg 30\)</span>.</p>
<p>We will consider all cases, but I will mainly be looking at the first and second scenario.</p>
<p>Below are the same simulation results seen in the first blog post. <em><strong>Note</strong>: I will not be showing any more <code>R</code> code as it mainly is creating plots and wrangling data.</em></p>
<pre class="r"><code>leave_long &lt;-  readRDS(here::here(&quot;static/data/monopoly_leave_long.rds&quot;))

stay_long &lt;- readRDS(here::here(&quot;static/data/monopoly_stay_long.rds&quot;))

leave_30 &lt;-  readRDS(here::here(&quot;static/data/monopoly_leave_30.rds&quot;))

stay_30 &lt;-  readRDS(here::here(&quot;static/data/monopoly_stay_30.rds&quot;))</code></pre>
<div id="which-sets-are-the-most-likely-to-be-landed-on" class="section level1">
<h1>Which sets are the most likely to be landed on?</h1>
<p>We can consider what sets are the best to own ,through aggregating by their group .</p>
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>From this we see that Orange is the best set to own based on the chances of ending a dice roll, with a 2.94% chance. This is followed closely by Red (2.92%) and Stations (2.84%). The worst three for chances are Brown (2.15%), Light Blue (2.30%), and Dark Blue (2.40%).</p>
<p>It should not be surprising as the best squares are those ahead of the jail square on board position 10, but they are also behind the go-to-jail square in position 30. The least common squares are furthest from the board changing actions.</p>
<p>Below is the same graph as before, but with different situation discussed earlier.</p>
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>We see that largely speaking the results are same.</p>
</div>
<div id="what-are-the-best-properties-in-terms-of-expected-income" class="section level1">
<h1>What are the best properties in terms of expected income?</h1>
<p>Once a property is bought by a player, they can charge rent on others who land on that property. Depending on if the player solely owns a property, owns properties of the same set, owns houses or hotels, that amount charged will differ.</p>
<p>As we have the probabilities of a player landing on a property, we can work out the expect income by using the formula.</p>
<p><span class="math display">\[
\text{Expected income per dice roll} = \text{P(landing on square per dice roll)} \times \text{income}
\]</span></p>
<p>Note that for utilities, the expected income will be 7, as that’s the average sum of two die, and for a set of utilities it would be <span class="math inline">\(10*7=70\)</span>.</p>
<div id="expected-income-for-base-rent" class="section level2">
<h2>Expected income for base rent</h2>
<p>We first consider the expected income per dice roll for just the property itself. We can consider the additional rent increases later.</p>
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" width="768" /></p>
<p>Generally speaking, we see that properties with higher rent tend to have higher expected income and almost looks like it follows the pattern of the boar itself. However there are a few differences. Vine Street (£0.49) has a slightly higher expected income than Fleet Street (£0.49), despite being in the “inferior” set. Moreover, Trafalgar Square (£0.64) is superior to all of Yellow’s expected income.</p>
<p>The stations also seem to provide a good chance at obtain steady income, though Liverpool Street Station (£0.61) seems to provide poor value when compared with other stations.</p>
<p>We can also group by colour to see which has the highest expected income.</p>
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>On average, we see that the Station set (£2.84) has the best highest expected income across it’s properties, followed by Dark Blue (£2.08). The worst two are Brown (£0.13) and Utilities (£0.38) .</p>
<p>We only considered the expected income when a player only owns a single property. We can extend the expected income to include the various upgrades such as having a full set, houses and hotels.</p>
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The graph suggests that with more upgrades a property obtains, the higher the additional expected rent. Mayfair usually has the highest expected income for each type of property extension. Curiously, Trafalgar square seems to best punching above it’s weight in terms of expected income.</p>
<p>We can also group the expected income by set</p>
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The above graph shows that the Green set with hotels has the highest expected income. The Brown set is the worst when it comes to expected income.</p>
<p>The biggest jump in income comes from jumping from two houses to three houses.</p>
</div>
<div id="for-other-scenarios" class="section level2">
<h2>For other scenarios</h2>
<p>We can also produce a similar visualizations for the other scenarios</p>
<p>I won’t be interpreting the results. But how do it remains the same; the larger the expected income, the better the property.</p>
<div id="for-many-rolls-and-staying-in-jail" class="section level3">
<h3>For many rolls and staying in jail</h3>
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>And by income set,</p>
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="for-30-dice-rolls-and-leaving-jail" class="section level3">
<h3>For 30 dice rolls and leaving jail</h3>
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>And by income set,</p>
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="for-30-dice-rolls-and-stay-in-jail" class="section level3">
<h3>For 30 dice rolls and stay in jail</h3>
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>And by income set,</p>
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
<div id="return-on-investment-on-properties" class="section level1">
<h1>Return on investment on properties</h1>
<p>While getting the property or set with the highest potential income may seem like a good idea, it does not take into account the costs required to obtain a property or reach a certain property level. A good indicator on whether something is of good value is by using the return on investment (ROI) metric. It basically measures how much money one can receive per amount spent.</p>
<p>The ROI is defined as.</p>
<p><span class="math display">\[
\text{ROI} \text{ %} =\frac{\text{Expected income}}{\text{Cost}} \text{ %} 
\]</span></p>
<p>We can also look to see how quickly we can make back our investments, by considering the number of opponent dice rolls it takes to recoup our investments. We define the “time” it takes become profitable as:</p>
<p><span class="math display">\[
\text{Number of opposition rolls to be profitable}  = \left \lceil{\frac{\text{Cost}}{\text{Expected income}}}\right \rceil = \left \lceil \frac{1}{\text{ROI %}}*100  \right \rceil
\]</span></p>
<p>We take the ceiling as if the number of opposition rolls is some decimal, say 5.8 dice rolls, then it is not yet profitable on the 5th dice roll, but it will be on the 6th. So we will round up the number of opposition rolls.</p>
<p>Let’s look at which one give the best bang for buck.</p>
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>According to the above chart, the best properties for return on investments are seen below:</p>
<table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Space
</th>
<th style="text-align:center;">
Group
</th>
<th style="text-align:center;">
Name
</th>
<th style="text-align:center;">
Type
</th>
<th style="text-align:center;">
ROI (%)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Vine Street
</td>
<td style="text-align:center;">
Hotel
</td>
<td style="text-align:center;">
4.41
</td>
</tr>
<tr>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Vine Street
</td>
<td style="text-align:center;">
4 Houses
</td>
<td style="text-align:center;">
4.12
</td>
</tr>
<tr>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Marlborough Street
</td>
<td style="text-align:center;">
Hotel
</td>
<td style="text-align:center;">
4.09
</td>
</tr>
<tr>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Bow Street
</td>
<td style="text-align:center;">
Hotel
</td>
<td style="text-align:center;">
3.90
</td>
</tr>
<tr>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Marlborough Street
</td>
<td style="text-align:center;">
4 Houses
</td>
<td style="text-align:center;">
3.79
</td>
</tr>
<tr>
<td style="text-align:center;">
39
</td>
<td style="text-align:center;">
Dark Blue
</td>
<td style="text-align:center;">
Mayfair
</td>
<td style="text-align:center;">
Hotel
</td>
<td style="text-align:center;">
3.75
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
Light Blue
</td>
<td style="text-align:center;">
Pentonville Road
</td>
<td style="text-align:center;">
Hotel
</td>
<td style="text-align:center;">
3.74
</td>
</tr>
<tr>
<td style="text-align:center;">
39
</td>
<td style="text-align:center;">
Dark Blue
</td>
<td style="text-align:center;">
Mayfair
</td>
<td style="text-align:center;">
4 Houses
</td>
<td style="text-align:center;">
3.72
</td>
</tr>
<tr>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Vine Street
</td>
<td style="text-align:center;">
3 Houses
</td>
<td style="text-align:center;">
3.71
</td>
</tr>
<tr>
<td style="text-align:center;">
39
</td>
<td style="text-align:center;">
Dark Blue
</td>
<td style="text-align:center;">
Mayfair
</td>
<td style="text-align:center;">
3 Houses
</td>
<td style="text-align:center;">
3.68
</td>
</tr>
</tbody>
</table>
<p>The Orange properties tend to have the highest ROI.</p>
<p>The worst are the properties not part of a set. The utilities by themselves are useless.</p>
<p>While ROI is a decent metric to tell if we something is a good deal or not, it does not tell us how long it will take to get good returns. By considering the number of opposition rolls it takes to turn a profit, we can obtain a good estimate for when we will break even.</p>
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" width="768" /></p>
<p>The above graphs shows the number of rolls needed to break even. The worst is Old Kent Road in no set which needs about 1,410 dice rolls before it generates a profit.</p>
<p>The table below shows properties and types that are the quickest at generating profit.</p>
<table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Space
</th>
<th style="text-align:center;">
Group
</th>
<th style="text-align:center;">
Name
</th>
<th style="text-align:center;">
Type
</th>
<th style="text-align:center;">
Opposition Rolls
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Vine Street
</td>
<td style="text-align:center;">
Hotel
</td>
<td style="text-align:center;">
23
</td>
</tr>
<tr>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Marlborough Street
</td>
<td style="text-align:center;">
Hotel
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Vine Street
</td>
<td style="text-align:center;">
4 Houses
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Bow Street
</td>
<td style="text-align:center;">
Hotel
</td>
<td style="text-align:center;">
26
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
Light Blue
</td>
<td style="text-align:center;">
Pentonville Road
</td>
<td style="text-align:center;">
Hotel
</td>
<td style="text-align:center;">
27
</td>
</tr>
<tr>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Marlborough Street
</td>
<td style="text-align:center;">
4 Houses
</td>
<td style="text-align:center;">
27
</td>
</tr>
<tr>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
Orange
</td>
<td style="text-align:center;">
Vine Street
</td>
<td style="text-align:center;">
3 Houses
</td>
<td style="text-align:center;">
27
</td>
</tr>
<tr>
<td style="text-align:center;">
39
</td>
<td style="text-align:center;">
Dark Blue
</td>
<td style="text-align:center;">
Mayfair
</td>
<td style="text-align:center;">
4 Houses
</td>
<td style="text-align:center;">
27
</td>
</tr>
<tr>
<td style="text-align:center;">
39
</td>
<td style="text-align:center;">
Dark Blue
</td>
<td style="text-align:center;">
Mayfair
</td>
<td style="text-align:center;">
Hotel
</td>
<td style="text-align:center;">
27
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
Light Blue
</td>
<td style="text-align:center;">
Euston Road
</td>
<td style="text-align:center;">
Hotel
</td>
<td style="text-align:center;">
28
</td>
</tr>
</tbody>
</table>
<p>The most common group that appears are the Oranges, followed by the Light Blue and Dark Blue groups. It also suggests placing hotels on properties generates profits the fastest.</p>
<p>Vine street also appears the most in the top 10 list; they are the best property to generate profit.</p>
</div>
<div id="property-sets-roi" class="section level1">
<h1>Property sets ROI</h1>
<p>We can group the properties by their sets to see the average performance.</p>
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We see that the Orange set with hotels is the set with the highest ROI % (4.14%) . Curiously, Light Blue has the second highest ROI % for hotels (3.66%).</p>
<p>We can also observe the number of opposition rolls required to start generating a profit.</p>
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We see that investing in 3 houses to hotels generates faster returns than the other upgrades.</p>
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" width="864" /></p>
<p>The above graphs shows how the ROI % changes by property type for different property sets. We see that, past 3 houses, Oranges are the best group and are the best for Hotel. Light Blue is surprisingly second for hotels, perhaps this due to the fact how cheap those properties are and how quickly it is to build houses and hotels.</p>
<p>Largely speaking, most sets do not improve in value for ROI past 3 houses - these are Red, Dark Blue, Yellow and Green.</p>
<p>Brown should be avoided as it does not generate great returns. However in the game, there are only a finite number of houses, so using the Browns to restrict the number of houses for other players might be a good strategy.</p>
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" width="864" /></p>
<p>The above graph shows the number of opposition rolls required to generate profit. We see that as the property set becomes more developed, the number of opposition rolls needed to generate a profit reaches a constant value. For all sets other than Brown, this constant number is about 30-40 rolls.</p>
<p>For Brown, it requires significantly more oppositions rolls before generat profit. It only become competitive with other sets when it has a hotel built.</p>
</div>
<div id="other-situations" class="section level1">
<h1>Other situations</h1>
<p>For the other situations we can view the charts.</p>
<p>I won’t be interpreting these, but they it follows the same process as before. The higher the ROI %, the better a property/property set is. The lower the number of opposition rolls, the better the property/property set is.</p>
<div id="for-many-dice-rolls-and-staying-at-jail" class="section level2">
<h2>For many dice rolls and staying at jail</h2>
<p><img src="index_files/figure-html/unnamed-chunk-25-1.png" width="768" style="display: block; margin: auto;" /></p>
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><img src="index_files/figure-html/unnamed-chunk-27-1.png" width="768" style="display: block; margin: auto;" /></p>
<p><img src="index_files/figure-html/unnamed-chunk-28-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="for-30-dice-rolls-leave-jail" class="section level2">
<h2>For 30 dice rolls leave jail</h2>
<p><img src="index_files/figure-html/unnamed-chunk-29-1.png" width="768" style="display: block; margin: auto;" /></p>
<p><img src="index_files/figure-html/unnamed-chunk-30-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><img src="index_files/figure-html/unnamed-chunk-31-1.png" width="768" style="display: block; margin: auto;" /></p>
<p><img src="index_files/figure-html/unnamed-chunk-32-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="for-30-dice-rolls-stay-in-jail" class="section level2">
<h2>For 30 dice rolls, stay in jail</h2>
<p><img src="index_files/figure-html/unnamed-chunk-33-1.png" width="768" style="display: block; margin: auto;" /></p>
<p><img src="index_files/figure-html/unnamed-chunk-34-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><img src="index_files/figure-html/unnamed-chunk-35-1.png" width="768" style="display: block; margin: auto;" /></p>
<p><img src="index_files/figure-html/unnamed-chunk-36-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="number-of-players" class="section level1">
<h1>Number of players</h1>
<p>From the 2017 edition onwards, the maximum number of players in a game of monopoly is 8[^1]. This means there are 7 opponents in the game. The minimin is 2, meaning there is 1 opponent.</p>
<p>[^1] :</p>
<p>We can calculate the expected income for a turn based on the number of opponents in the game. This different from the number of dice rolls. To calculate the number of expected dice rolls per player turn, we can simply add up the possibilities as follows:</p>
<p><span class="math display">\[
\begin{align}
\text{Expected # dice rolls per turn} &amp;= \bigg(\overbrace{\frac{5}{6} \times 1  }^{\text{1 single, 0 doubles}}\bigg)
+ \bigg( \overbrace{\frac{1}{6} \times \frac{5}{6} \times 2}^{\text{1 single, 1 double}} \bigg) 
+ \bigg( \overbrace{\frac{1}{6^2} \times \frac{5}{6} \times 3}^{\text{2 singles, 1 double}} \bigg)
+ \bigg( \overbrace{\frac{1}{6^3} \times 3}^{\text{0 singles, 3 doubles}} \bigg) \\
&amp;= \frac{43}{36}\\
&amp;\approx 1.19
\end{align}
\]</span></p>
<p>Thus we see that a player can expect roll the dice 1.19 times a turn.</p>
<p>We can work out how many total turns it will take for a set to pay itself off. We can calculate this as</p>
<p><span class="math display">\[
\text{Number of turns} = \frac{\text{# Opposition rolls to generate profit}}{\text{Expected # dice rolls per turn} \times \text{# of players}}
\]</span></p>
<p>We can see how quickly a set will take to start to generate income based based on the number of turns by looking at the interactive table below.</p>
<div id="htmlwidget-1" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"filter":"top","filterHTML":"<tr>\n  <td><\/td>\n  <td data-type=\"factor\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"width: 100%; display: none;\">\n      <select multiple=\"multiple\" style=\"width: 100%;\" data-options=\"[&quot;Brown&quot;,&quot;Light Blue&quot;,&quot;Pink&quot;,&quot;Orange&quot;,&quot;Red&quot;,&quot;Yellow&quot;,&quot;Green&quot;,&quot;Dark Blue&quot;]\"><\/select>\n    <\/div>\n  <\/td>\n  <td data-type=\"factor\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"width: 100%; display: none;\">\n      <select multiple=\"multiple\" style=\"width: 100%;\" data-options=\"[&quot;No Set&quot;,&quot;Full Set&quot;,&quot;1 House&quot;,&quot;2 Houses&quot;,&quot;3 Houses&quot;,&quot;4 Houses&quot;,&quot;Hotel&quot;]\"><\/select>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none; position: absolute; width: 200px;\">\n      <div data-min=\"21\" data-max=\"779\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none; position: absolute; width: 200px;\">\n      <div data-min=\"10\" data-max=\"389\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none; position: absolute; width: 200px;\">\n      <div data-min=\"7\" data-max=\"260\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none; position: absolute; width: 200px;\">\n      <div data-min=\"5\" data-max=\"195\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none; position: absolute; width: 200px;\">\n      <div data-min=\"4\" data-max=\"156\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none; position: absolute; width: 200px;\">\n      <div data-min=\"3\" data-max=\"130\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none; position: absolute; width: 200px;\">\n      <div data-min=\"3\" data-max=\"111\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56"],["Brown","Brown","Brown","Brown","Brown","Brown","Brown","Light Blue","Light Blue","Light Blue","Light Blue","Light Blue","Light Blue","Light Blue","Pink","Pink","Pink","Pink","Pink","Pink","Pink","Orange","Orange","Orange","Orange","Orange","Orange","Orange","Red","Red","Red","Red","Red","Red","Red","Yellow","Yellow","Yellow","Yellow","Yellow","Yellow","Yellow","Green","Green","Green","Green","Green","Green","Green","Dark Blue","Dark Blue","Dark Blue","Dark Blue","Dark Blue","Dark Blue","Dark Blue"],["No Set","Full Set","1 House","2 Houses","3 Houses","4 Houses","Hotel","No Set","Full Set","1 House","2 Houses","3 Houses","4 Houses","Hotel","No Set","Full Set","1 House","2 Houses","3 Houses","4 Houses","Hotel","No Set","Full Set","1 House","2 Houses","3 Houses","4 Houses","Hotel","No Set","Full Set","1 House","2 Houses","3 Houses","4 Houses","Hotel","No Set","Full Set","1 House","2 Houses","3 Houses","4 Houses","Hotel","No Set","Full Set","1 House","2 Houses","3 Houses","4 Houses","Hotel","No Set","Full Set","1 House","2 Houses","3 Houses","4 Houses","Hotel"],[779,389,285,139,61,43,35,582,291,171,81,33,27,23,458,229,154,73,33,28,28,363,182,111,54,25,23,21,348,174,116,57,28,27,27,372,186,116,53,28,28,28,373,187,121,56,32,32,33,303,152,106,49,28,28,28],[389,195,143,69,31,21,18,291,146,85,41,17,13,12,229,115,77,36,16,14,14,181,91,56,27,13,11,10,174,87,58,28,14,13,13,186,93,58,26,14,14,14,186,93,60,28,16,16,16,152,76,53,25,14,14,14],[260,130,95,46,20,14,12,194,97,57,27,11,9,8,153,76,51,24,11,9,9,121,61,37,18,8,8,7,116,58,39,19,9,9,9,124,62,39,18,9,9,9,124,62,40,19,11,11,11,101,51,35,16,9,9,9],[195,97,71,35,15,11,9,145,73,43,20,8,7,6,114,57,39,18,8,7,7,91,45,28,13,6,6,5,87,44,29,14,7,7,7,93,46,29,13,7,7,7,93,47,30,14,8,8,8,76,38,27,12,7,7,7],[156,78,57,28,12,9,7,116,58,34,16,7,5,5,92,46,31,15,7,6,6,73,36,22,11,5,5,4,70,35,23,11,6,5,5,74,37,23,11,6,6,6,75,37,24,11,6,6,7,61,30,21,10,6,6,6],[130,65,48,23,10,7,6,97,49,28,14,6,4,4,76,38,26,12,5,5,5,60,30,19,9,4,4,3,58,29,19,9,5,4,4,62,31,19,9,5,5,5,62,31,20,9,5,5,5,51,25,18,8,5,5,5],[111,56,41,20,9,6,5,83,42,24,12,5,4,3,65,33,22,10,5,4,4,52,26,16,8,4,3,3,50,25,17,8,4,4,4,53,27,17,8,4,4,4,53,27,17,8,5,5,5,43,22,15,7,4,4,4]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Group<\/th>\n      <th>Property Type<\/th>\n      <th>1 Opponents<\/th>\n      <th>2 Opponents<\/th>\n      <th>3 Opponents<\/th>\n      <th>4 Opponents<\/th>\n      <th>5 Opponents<\/th>\n      <th>6 Opponents<\/th>\n      <th>7 Opponents<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[3,4,5,6,7,8,9]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false,"orderCellsTop":true}},"evals":[],"jsHooks":[]}</script>
<p>The table shows how many players turns it will take for a set and proprty type to pay itself of depending on the number of players read off the number of</p>
<p>The way to use it would be to select a group and property type and then read off the number of turns it would take to pay off the investment.</p>
</div>
<div id="earning-over-competitor-rolls" class="section level1">
<h1>Earning over competitor rolls</h1>
<p><img src="index_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>The above graph shows the expected profit after several dice rolls. When part of a full set, Dark Blue gives the best long term expected income, however has the set becomes more developed, Green becomes the superior set.</p>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>Overall when looking at the the result of many dice rolls, with the strategy of leaving jail we can obtain the following conclusions:</p>
<p><em>(You can draw similar results for the different scenarios by looking at the graphs)</em></p>
<p>For expected income per dice roll by property:</p>
<ul>
<li><p>The properties with the highest expected income are: Mayfair (£1.31), Park Lane (£0.76), and Bond Street (£0.70).</p></li>
<li><p>For hotels, and houses, it’s: Mayfair w/ Hotel (£52.53), Mayfair w/ 4 houses (£44.65), Mayfair w/ 3 Houses (£36.77), and Trafalgar Square w/ Hotel (£35.06)</p></li>
</ul>
<p>For expected income per dice roll by property set:</p>
<ul>
<li><p>The best property groups by expected outcome are: Dark Blue (£2.08), Green (£2.07), and Yellow (£2.07)</p></li>
<li><p>For hotels and houses: Green w/ Hotel (£102.26), Red w/ Hotel (£93.43), Yellow w/ (£92.87)</p></li>
</ul>
<p>For the best property for in terms of ROI %:</p>
<ul>
<li><p>For the base level: Mayfair (0.44%), Trafalgar Square (0.27%), and Vine Street (0.22%)</p></li>
<li><p>For hotels and houses: Vine Street w/ Hotel (4.41%), Vine Street w/ 3 Houses (4.12%), and Marlborough Street w/ Hotel (4.09%).</p></li>
</ul>
<p>For the best property sets in terms of ROI %:</p>
<ul>
<li><p>For the base level: Dark Blue (0.28%) and Red (0.24%)</p></li>
<li><p>For hotels and houses: Orange w/ Hotel (4.14%), Orange w/ 4 Houses (3.84%), and Light Blue (3.66%)</p></li>
</ul>
<p>For most property sets, the ROI % does not improve after 3 houses. The exceptions are: Orange, Light Blue, Pink and Brown.</p>
<p>After 3 houses have been developed, the number of opposition rolls required to pay off the cost generally remains constant.</p>
<p>In the long run, after many dice rolls, the Green set generates the highest profit.</p>
<p>The major takeaway is that the best set to aim for in terms of ROI is Orange, in terms of expected income it’s Green. If you have a set, you should aim to build 3 houses as it provides the ROI on average.</p>
<pre class="r"><code>sessionInfo()</code></pre>
<pre><code>## R version 4.0.3 (2020-10-10)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 19041)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_United Kingdom.1252 
## [2] LC_CTYPE=English_United Kingdom.1252   
## [3] LC_MONETARY=English_United Kingdom.1252
## [4] LC_NUMERIC=C                           
## [5] LC_TIME=English_United Kingdom.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] ggtext_0.1.0    patchwork_1.1.1 forcats_0.5.0   stringr_1.4.0  
##  [5] dplyr_1.0.2     purrr_0.3.4     readr_1.4.0     tidyr_1.1.2    
##  [9] tibble_3.0.3    ggplot2_3.3.2   tidyverse_1.3.0
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_1.0.5        lubridate_1.7.9   here_1.0.1        ps_1.4.0         
##  [5] assertthat_0.2.1  rprojroot_2.0.2   digest_0.6.25     R6_2.4.1         
##  [9] cellranger_1.1.0  backports_1.1.10  reprex_0.3.0      evaluate_0.14    
## [13] highr_0.8         httr_1.4.2        blogdown_0.21     pillar_1.4.6     
## [17] rlang_0.4.7       readxl_1.3.1      rstudioapi_0.11   blob_1.2.1       
## [21] DT_0.16           rmarkdown_2.5     labeling_0.4.2    webshot_0.5.2    
## [25] htmlwidgets_1.5.2 munsell_0.5.0     gridtext_0.1.1    broom_0.7.2      
## [29] compiler_4.0.3    modelr_0.1.8      xfun_0.18         pkgconfig_2.0.3  
## [33] htmltools_0.5.0   tidyselect_1.1.0  bookdown_0.21     fansi_0.4.1      
## [37] viridisLite_0.3.0 crayon_1.3.4      dbplyr_1.4.4      withr_2.3.0      
## [41] grid_4.0.3        jsonlite_1.7.1    gtable_0.3.0      lifecycle_0.2.0  
## [45] DBI_1.1.0         magrittr_1.5      scales_1.1.1      cli_2.1.0        
## [49] stringi_1.5.3     farver_2.0.3      fs_1.5.0          xml2_1.3.2       
## [53] ellipsis_0.3.1    generics_0.0.2    vctrs_0.3.4       kableExtra_1.3.1 
## [57] tools_4.0.3       glue_1.4.2        markdown_1.1      crosstalk_1.1.0.1
## [61] hms_0.5.3         yaml_2.2.1        colorspace_1.4-1  rvest_0.3.6      
## [65] knitr_1.30        haven_2.3.1</code></pre>
</div>
